#!/bin/sh

# second-stage init. kernel filesystems and work overlay are up, hook it all
# up and get a shell

# at least make the prompt look nice
hostname quiz

# get modules into place. we do this at the top instead of in profile because
# we're pretty much always gonna need this
mount --bind /work/lib/modules /lib/modules

# if any profiles need work, boot them up
if [ -r /work/.quiz/init.profile ] ; then
  echo "quiz: starting profile init" >> /dev/kmsg
  . /work/.quiz/init.profile
fi

echo "quiz: starting user program" >> /dev/kmsg

# start a "real" init, and run our program
if [ -r /work/.quiz/run ] ; then
  exec tini -vwsg /work/.quiz/run
fi

# no program, just go to a shell
exec tini -vwsg /bin/bash
