#!/bin/sh
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-2025, Rob Norris <robn@despairlabs.com>

# first-stage init; getting the filesystems up, then we bounce into the
# second-stage init in the quiz work dir

# bring the local dirs in
for dir in init user kernel system ; do
  mount -t 9p -o trans=virtio quiz-$dir /mnt/quiz-$dir \
  -oversion=9p2000.L,posixacl,msize=512000,cache=loose
done

# build the root overlay. this is creating this layering:
#
#   tmpfs           /mnt/overlay/upper [rw]
#   quiz init dir   /mnt/quiz-init     [ro]
#   quiz user dir   /mnt/quiz-user     [ro]
#   quiz kernel dir /mnt/quiz-kernel   [ro]
#   quiz system dir /mnt/quiz-system   [ro]
#   root.ext2       /                  [ro]
#
# the overlay is then mounted at /mnt/newroot
mount -t tmpfs tmpfs /mnt/overlay
mkdir /mnt/overlay/upper /mnt/overlay/work
mount --bind / /mnt/lower
mount -t overlay overlay -o lowerdir=/mnt/quiz-init:/mnt/quiz-user:/mnt/quiz-kernel:/mnt/quiz-system:/mnt/lower,upperdir=/mnt/overlay/upper,workdir=/mnt/overlay/work /mnt/newroot

# make /mnt/newroot the new /. after the pivot, the original root is on /mnt
pivot_root /mnt/newroot /mnt/newroot/mnt

# mount kernel filesystems
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts

# unmount the overlay components mounts, no longer needed (the overlay is still
# holding references under the hood; this just removes them from the visible
# filesystem hierarchy. we use --lazy because this seems to be very slightly
# racy and sometimes leaves one or more still mounted; it hardly matters, we're
# just trying to tidy up
umount --lazy /mnt/mnt/lower
umount --lazy /mnt/mnt/overlay
umount --lazy /mnt/mnt/quiz-system
umount --lazy /mnt/mnt/quiz-kernel
umount --lazy /mnt/mnt/quiz-user
umount --lazy /mnt/mnt/quiz-init
umount --lazy /mnt

# bounce into the second stage
exec /.quiz/init2

# vim: ft=sh
