#!/bin/sh

# second-stage init. filesystem is up, now actually boot the system and run
# the user program

# at least make the prompt look nice
hostname quiz

# start udev. we need device node support
/lib/systemd/systemd-udevd &
udevadm trigger -t subsystems
udevadm trigger -t devices
udevadm settle

# if any profiles need work, boot them up
if [ -r /.quiz/init.profile ] ; then
  . /.quiz/init.profile
fi

echo "quiz: starting user program" >> /dev/kmsg

# start a "real" init, and run our program
if [ -r /.quiz/run ] ; then
  exec tini -vwsg /bin/sh -- -x /.quiz/run
fi

# no program, just go to a shell
exec tini -vwsg /bin/bash
