#!/bin/sh

# second-stage init. kernel filesystems and work overlay are up, hook it all
# up and get a shell

hostname quiz

mount --bind /work/lib/modules /lib/modules
mount --bind /work/zfs /zfs

insmod /lib/modules/$(uname -r)/extra/spl.ko
insmod /lib/modules/$(uname -r)/extra/zfs.ko

if grep -qs "quiz\.formatdevs=1" /proc/cmdline ; then
  sgdisk -ZN0 /dev/vdb
  sgdisk -ZN0 /dev/vdc
fi

export PATH=/zfs/sbin:$PATH

if grep -qs "quiz\.createpool=1" /proc/cmdline ; then
  zpool create -f -O atime=off tank mirror /dev/vdb1 /dev/vdc1
elif grep -qs "quiz\.importpool=1" /proc/cmdline ; then
  zpool import -d /dev/vdb1 tank
fi

zpool status

exec tini -vwsg /work/.quiz/run
