#!/bin/sh
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-2025, Rob Norris <robn@despairlabs.com>

# "tmux" rc, for easier interactive use.
#
# we run tmux inside the VM, with two windows:
#   0: kernel output (dmesg)
#   1: actual program run
#
# this script gets tmux launched, with the the windows set up. rc/tmux/main is
# what actually gets run in the "main" window

# disable kernel output direct to console, so it doesn't scribble all over tmux
# itself. dmesg is then run in the first window to get the log in a more
# contained fashion
dmesg -n 1

# start tmux. the config file is mostly for styles and colours. we force
# 256-color and unicode support here, because my terminal handles it and in
# 2025, yours should too.
tmux -2u -f /.quiz/rc/tmux.conf \
  new-session -n 'dmesg' dmesg -w \; \
  new-window -n 'run' /.quiz/rc/main \; \

# vim: ft=sh
