#!/bin/sh

mount -t sysfs none /sys
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp

hostname zfs-qemu

mkdir /tmp/overlay
mount -t 9p -o trans=virtio overlay /tmp/overlay \
  -oversion=9p2000.L,posiixacl,msize=104857600,cache=loose

mount --bind /tmp/overlay/lib/modules /lib/modules
mount --bind /tmp/overlay/opt /opt

insmod /lib/modules/$(uname -r)/extra/spl.ko
insmod /lib/modules/$(uname -r)/extra/zfs.ko

exec tini -vwsg /bin/bash
