#!/bin/sh

mount -t sysfs none /sys
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp

hostname quiz

mkdir /tmp/overlay
mount -t 9p -o trans=virtio overlay /tmp/overlay \
  -oversion=9p2000.L,posiixacl,msize=104857600,cache=loose

mount --bind /tmp/overlay/lib/modules /lib/modules
mount --bind /tmp/overlay/opt /opt

insmod /lib/modules/$(uname -r)/extra/spl.ko
insmod /lib/modules/$(uname -r)/extra/zfs.ko

if grep -qs "quiz\.formatdevs=1" /proc/cmdline ; then
  sgdisk -ZN0 /dev/vdb
  sgdisk -ZN0 /dev/vdc
fi

export PATH=/opt/openzfs/sbin:$PATH

if grep -qs "quiz\.createpool=1" /proc/cmdline ; then
  zpool create -f -O atime=off tank mirror /dev/vdb1 /dev/vdc1
elif grep -qs "quiz\.importpool=1" /proc/cmdline ; then
  zpool import -d /dev/vdb1 tank
fi

zpool status

exec tini -vwsg /bin/bash
