#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

trace() {
  local STAMP=$( date '+%Y%m%d-%H:%M:%S' )
  echo "[zfs-qemu-prepare-overlay] ${STAMP} $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(dirname $0)

cd $RUNDIR
if [[ ! -d kernel ]] ; then
  fail "didn't find kernel dir, you might need to run prepare-kernel first"
fi

trace "install kernel module structure"

mkdir -p libexec/overlay
make -C kernel/linux-5.10.170 install modules_install \
  INSTALL_PATH=$PWD/libexec/overlay INSTALL_MOD_PATH=$PWD/libexec/overlay

mkdir -p libexec/overlay/opt

trace "done"
