#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

trace() {
  local STAMP=$( date '+%Y%m%d-%H:%M:%S' )
  echo "[zfs-qemu-prepare-root] ${STAMP} $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(dirname $0)

cd $RUNDIR

trace "building root image"

mmdebstrap \
  --variant=minbase \
  --include=tini,coreutils,procps,kmod,gdisk \
    --customize-hook='install -m 755 init "$1"/sbin/init' \
    --customize-hook='mkdir "$1"/lib/modules' \
    --customize-hook='mkdir "$1"/tank' \
  bullseye libexec/root.ext2

trace "done"
