#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

trace() {
  local STAMP=$( date '+%Y%m%d-%H:%M:%S' )
  echo "[quiz-prepare-kernel] ${STAMP} $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(dirname $0)

cd $RUNDIR

if [[ ! -d kernel ]] ; then
  trace "preparing kernel source"
  mkdir -p kernel
  cd kernel
  curl -O https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.170.tar.xz
  tar xfJ linux-5.10.170.tar.xz
  cd ..
  cp config-5.10 kernel/linux-5.10.170/.config
fi

trace "building kernel"

cd kernel/linux-5.10.170
make olddefconfig
make -j8
cd ../..

trace "moving completed kernel into place"

mkdir -p libexec
cp kernel/linux-5.10.170/arch/x86/boot/bzImage libexec

trace "done"
