#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright (c) 2023, Rob Norris <robn@despairlabs.com>

#
# Linux source version numbers (the tarball version) don't always match their
# installed version number (module dir version, uname -a output), eg:
#
#   source    installed
#   6.9-rc1   6.9.0-rc1
#   6.9       6.9.0
#   6.9.1     6.9.1
#
# we allow any form. internally, we'll set up variables for the "version"
# (installed) and "source version" (source), and also vars for all the pieces
#

function quiz_kernel_vars () {
  local kver="${1:-}"
  if [[ -z $kver ]] ; then
    fail "no kernel version set. use -k or set QUIZ_KERNEL_VERSION"
  fi

  _quiz_kver=""
  _quiz_ksrcver=""
  _quiz_kmajor=""
  _quiz_kminor=""
  _quiz_kpatch=""
  _quiz_ktype=""
  _quiz_ktype_patch=""

  shopt -s lastpipe
  echo $kver | perl -nE '
    ($maj, $min, $pat, $ty, $typat) = m/
      ^
        ([1-9][0-9]*)               # major
        \.                          # dot sep
        (0|[1-9][0-9]*)             # minor
        (?:\.(0|[1-9][0-9]*))?      # patch 1+, optionl
        (?:-(rc)([1-9][0-9]*))?     # type & typepatch
      $
    /gx;
    $pat //= 0;
    print qq{$maj $min $pat $ty $typat}
  ' | read _quiz_kmajor _quiz_kminor _quiz_kpatch _quiz_ktype _quiz_ktype_patch

  if [[ -z $_quiz_kmajor || -z $_quiz_kminor ]] ; then
    fail "'$kver' is not a valid kernel version"
  fi
  if [[ -z $_quiz_kpatch ]] ; then
    _quiz_kpatch="0"
  fi
  if [[ -z $_quiz_ktype ]] ; then
    _quiz_ktype='release'
    _quiz_ksrcver=$_quiz_kmajor.$_quiz_kminor
    _quiz_kver=$_quiz_ksrcver
    if [[ "$_quiz_kpatch" = "0" ]] ; then
      _quiz_kver="$_quiz_kver.0"
    else
      _quiz_kver="$_quiz_kver.$_quiz_kpatch"
      _quiz_ksrcver="$_quiz_ksrcver.$_quiz_kpatch"
    fi
  elif [[ $_quiz_ktype == "rc" ]] ; then
    _quiz_kver=$_quiz_kmajor.$_quiz_kminor.0-$_quiz_ktype$_quiz_ktype_patch
    _quiz_ksrcver=$_quiz_kmajor.$_quiz_kminor-$_quiz_ktype$_quiz_ktype_patch
  fi
}
