#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright (c) 2023, Rob Norris <robn@despairlabs.com>

set -uo pipefail

usage() {
  cat <<EOF
compile a kernel optimised for the quiz microvm
usage: quiz-prepare-kernel [opts]

options:
  -k <kernel>     kernel to build
  -C              don't replace kernel config with our own
  -B              prepare build tree & config, don't build
  -h              this help
EOF
  exit 1
}

trace() {
  local STAMP=$(date +%Y%m%d-%H:%M:%S)
  echo "[quiz-prepare-kernel] $STAMP $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR


RUNDIR=$(realpath $(dirname $0))
source $RUNDIR/quiz-config
source $RUNDIR/quiz-lib

opt_kernel=""
opt_no_config=""
opt_no_build=""

OPTIND=1
while getopts "k:CBh" opt
do
  case "$opt" in
    'k') opt_kernel=$OPTARG ;;
    'C') opt_no_config=1 ;;
    'B') opt_no_build=1 ;;
    'h') usage ;;
    *) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)

cd $RUNDIR

QUIZ_KERNEL_VERSION=${opt_kernel:-$QUIZ_KERNEL_VERSION}
quiz_explode_kernel_version

mkdir -p build
if [[ -d build/kernel/linux-$_quiz_ksrcver ]] ; then
  trace "using existing source dir: build/kernel/linux-$_quiz_ksrcver"
else
  trace "setting up for build in: build/kernel/linux-$_quiz_ksrcver"
  mkdir -p build/kernel
  pushd build/kernel
  if [[ -f $_quiz_ktar ]] ; then
    trace "using existing tarball: $_quiz_ktar"
  else
    trace "downloading: $_quiz_kurl"
    curl -fOL $_quiz_kurl
  fi
  tar xf$_quiz_kzopt $_quiz_ktar
  popd
fi

kcfg=config-$_quiz_kmajor.$_quiz_kminor
if [[ ! -f kernel/$kcfg ]] ; then
  kcfg=$(ls kernel/config-$_quiz_kmajor.* | cut -f2 -d/ | tail -1)
fi
if [[ ! -f kernel/$kcfg ]] ; then
  kcfg=$(ls kernel/config-* | cut -f2 -d/ | tail -1)
fi

if [[ -z $opt_no_config ]] ; then
  trace "installing config: $kcfg"
  cp kernel/$kcfg build/kernel/linux-$_quiz_ksrcver/.config
fi

trace "building kernel: $_quiz_kver"

pushd build/kernel/linux-$_quiz_ksrcver
make olddefconfig

if [[ -n $opt_no_build ]] ; then
  trace "stopping before build as requested"
  popd
  exit 0
fi

make -j5
popd

trace "moving completed kernel into place"

mkdir -p system
cp build/kernel/linux-$_quiz_ksrcver/arch/x86/boot/bzImage system/bzImage-$_quiz_kver

trace "done"

# vim: ft=bash
