#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright (c) 2023, Rob Norris <robn@despairlabs.com>

set -uo pipefail

usage() {
  cat <<EOF
create a minimal root filesystem for the quiz microvm
usage: quiz-prepare-root
EOF
  exit 1
}

trace() {
  local STAMP=$(date +%Y%m%d-%H:%M:%S)
  echo "[quiz-prepare-root] $STAMP $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(realpath $(dirname $0))
source $RUNDIR/quiz-config

OPTIND=1
while getopts "h" opt
do
  case "$opt" in
    'h') usage ;;
    *) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)

trace "building root image"

zfs_extras=libtirpc3
zfstest_extras=bc,bzip2,cpio,file,fio,acl,sysstat,samba-common-bin,openssl,pamtester,pax,iputils-ping,python3-minimal,rsync,openssh-client,binutils,attr,nfs-kernel-server,lsscsi,parted,linux-base
debug_extras=jq,gdb,strace,fio,bpftrace,linux-perf,xxd,blktrace,mdadm

mmdebstrap \
  --variant=minbase \
  --include=tini,udev,coreutils,procps,kmod,gdisk,dmsetup,ksh,tmux,$zfs_extras,$zfstest_extras,$debug_extras \
    --customize-hook='install -m 755 init/init1 "$1"/sbin/init' \
    --customize-hook='mkdir "$1"/mnt/quiz-init "$1"/mnt/quiz-system "$1"/mnt/quiz-user' \
    --customize-hook='mkdir "$1"/mnt/lower "$1"/mnt/overlay "$1"/mnt/newroot' \
  $QUIZ_DEBIAN_RELEASE $RUNDIR/system/$QUIZ_DEBIAN_RELEASE.ext2

trace "done"

# vim: ft=bash
