#!/usr/bin/env bash
set -uo pipefail

trace() {
  local STAMP=$(date +%Y%m%d-%H:%M:%S)
  echo "[quiz-prepare-root] $STAMP $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(realpath $(dirname $0))

trace "building root image"

mmdebstrap \
  --variant=minbase \
  --include=tini,coreutils,procps,kmod,gdisk \
    --customize-hook='install -m 755 init/init1 "$1"/sbin/init' \
    --customize-hook='mkdir "$1"/work "$1"/zfs "$1"/lib/modules "$1"/tank' \
  bullseye $RUNDIR/system/root.ext2

trace "done"
