#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

trace() {
  local STAMP=$( date '+%Y%m%d-%H:%M:%S' )
  echo "[quiz-prepare-work] ${STAMP} $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(realpath $(dirname $0))

cd $RUNDIR
if [[ ! -d build/kernel ]] ; then
  fail "didn't find kernel dir, you might need to run quiz-prepare-kernel first"
fi

trace "install kernel module structure"

rm -rf system/work
mkdir -p system/work
make -C build/kernel/linux-5.10.170 install modules_install \
  INSTALL_PATH=$RUNDIR/system/work INSTALL_MOD_PATH=$RUNDIR/system/work

mkdir -p system/work/z

trace "done"
