#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

trace() {
  local STAMP=$( date '+%Y%m%d-%H:%M:%S' )
  echo "[quiz-prepare-root] ${STAMP} $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

RUNDIR=$(realpath $(dirname $0))

trace "building root image"

mmdebstrap \
  --variant=minbase \
  --include=tini,coreutils,procps,kmod,gdisk \
    --customize-hook='install -m 755 root/init "$1"/sbin/init' \
    --customize-hook='mkdir "$1"/lib/modules' \
    --customize-hook='mkdir "$1"/quiz' \
    --customize-hook='mkdir "$1"/z' \
  bullseye $RUNDIR/system/root.ext2

trace "done"
