#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright (c) 2023, Rob Norris <robn@despairlabs.com>

set -uo pipefail

usage() {
  cat <<EOF
build OpenZFS with options to work well with quiz
usage: quiz-build-zfs [opts] <configure|make> [program args...]

options:
  -k <kernel>
        kernel to use for this run
  -h    this help
EOF
  exit 1
}

trace() {
  local STAMP=$(date +%Y%m%d-%H:%M:%S)
  echo "[quiz-build-zfs] $STAMP $@" >&2
}

fail() {
  trace "FATAL $@"
  exit 1
}
trap fail ERR

do_configure() {
  exec ./configure \
    --with-linux=$RUNDIR/build/kernel/linux-$_quiz_ksrcver \
    --with-linux-obj=$RUNDIR/build/kernel/linux-$_quiz_ksrcver \
    --prefix=/usr/local \
    --disable-sysvinit \
    --disable-systemd \
    --disable-pam \
    'lt_cv_sys_lib_dlsearch_path_spec=/lib /usr/lib /lib/i686-linux-gnu /usr/lib/x86_64-linux-gnu' \
    "$@"
}

do_make() {
  exec make "$@"
}

do_make_install() {
  exec make install \
    DESTDIR=$RUNDIR/system/work \
    "$@"
}

RUNDIR=$(realpath $(dirname $0))
source $RUNDIR/quiz-config
source $RUNDIR/quiz-lib

opt_new=0
opt_kernel=""

OPTIND=1
while getopts "k:h" opt
do
  case "$opt" in
    'k') opt_kernel=$OPTARG ;;
    'h') usage ;;
    *) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)

if [[ $# -lt 1 ]] ; then
  usage
fi

quiz_select_kernel $opt_kernel
quiz_explode_kernel_version

case "$1" in
  configure) do_configure "${@:2}" ;;
  make)
    if [[ $# -ge 2 && $2 == install ]] ; then
      do_make_install "${@:3}"
    fi
    do_make "${@:2}"
    ;;
  *) usage ;;
esac

# vim: ft=bash
