#!/bin/sh

# "raw" rc. just the kernel and program output, all in one, good for piping and
# redirecting.

# In order for signals to be delivered, we need to run the program in a pty.
# Amazingly, I couldn't find a single simple program that would allocate one
# and run the program. Turns out that `script` is pretty close though, if we
# just dump its "log" elsewhere. Maybe that's the "single simple program" after
# all.
exec script -q -e \
  -c '/bin/sh -- /.quiz/run' \
  /dev/null
